### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by picsi** [kickstarter/android-oss#10]
It would be neat to have this at the F-Droid repository: https://f-droid.org/

**Comment by Jawnnypoo** [comment]
I doubt this will ever be possible since the app contains dependencies that are not FOSS, such as Google Play Services. See https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by luoser** [comment]
yep, @Jawnnypoo hit the nail on the head. thanks for the suggestion tho!
