### ISSUE TITLE
Project migration to the component based architecture / Kotlin

### ISSUE THREAD

**Issue by selmanon** [kickstarter/android-oss#103]
Hello,

Is there any plan to migrate the projet to an component based architecture ?
Same to start using Kotlin for new features ?

Best,
Abdellah

**Comment by onmyway133** [comment]
I see they are using kotlin https://github.com/kickstarter/android-oss/blob/master/app/build.gradle#L152 to some degree. 

I hope you will consider kotlin for future features 🚀

**Comment by luoser** [comment]
Yep, we're using Kotlin as we see fit for new utils and some classes. The Hope and Dream™ is to get most of our view models, activities, and tests (i.e. everything hehe) to Kotlin, but to keep with our product roadmaps it's not our priority right now 😭
