### ISSUE TITLE
Move from Manual version bumps to Dependabot

### ISSUE THREAD

**Issue by apoorv-arora** [kickstarter/android-oss#1483]
**Overview**
Dependabot takes the effort out of maintaining our dependencies. We can use it to ensure that our repository automatically keeps up with the latest releases of the packages and applications it depends on. 

Learn more [here](https://docs.github.com/github/administering-a-repository/keeping-your-dependencies-updated-automatically).

**Comment by Arkariang** [comment]
It's a great suggestion! once we've had the chance to modernize some of our dependencies we could explore it for sure 💯
