### ISSUE TITLE
Can't use source code

### ISSUE THREAD

**Issue by lalitsharmaking** [kickstarter/android-oss#1647]
I am very new to coding and I have tried everything searched everywhere but can't understand the meaning of - " cd in the project repo or how to run bootstrap " can someone help me because I tried to open this project without it and it's showing error

**Comment by mark2185** [comment]
The instructions say:
```
cd into the project repo and run make bootstrap to bootstrap your Android development environment. Keep an eye on the output to see if any manual steps are required.
```

That means that you should run the following:
```
git clone https://github.com/kickstarter/android-oss.git
```

And then `cd` into it:
```
cd android-oss
```

And then run `make bootstrap`. The output should say if any manual steps are required.

What happens when you follow these instructions?

**Comment by lalitsharmaking** [comment]
i  have succesfully resolved these problems but there are new problems in the code 
`    // Copy google-services.json from variant directory to root of app

gradle.taskGraph.beforeTask { Task task ->
    if (task.name ==~ /process.*GoogleServices/) {
        android.applicationVariants.all { variant ->
            if (task.name ==~ /(?i)process${variant.name}GoogleServices/) {
                copy {
                    from "src/${variant.name}"
                    into '.'
                    include 'google-services.json'
                }
            }
        }
    }
}
`
it is saying cannot resolve symbol task would be greatful if u can help

**Comment by mark2185** [comment]
> would be greatful if u can help

Sadly, I can't. I never even heard of this project before you mentioned it on `lazygit's` issue board.

Hopefully someone from the dev team can help you. Good luck!

**Comment by lalitsharmaking** [comment]
` kotlinOptions {
    jvmTarget = JavaVersion.VERSION_11.toString()
    useIR = true
}
`
 it is also saying - a problem occured while evaluating the app

caused by : [groovy.lang.MissingPropertyException: Could not set unknown property 'useIR' for object of type org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptionsImpl](https://stackoverflow.com/questions/72790822/groovy-lang-missingpropertyexception-could-not-set-unknown-property-useir-for)

**Comment by lalitsharmaking** [comment]
thank you brother for your response

**Comment by Arkariang** [comment]
Hello there @lalitsharmaking , the error indicates that some of the Firebase `google-services.json` are not available, as those are private configuration files, but there are some templates on the repository such as https://github.com/kickstarter/android-oss/blob/master/config/externalDebug/google-services.example.json 
You can simple rename those files taking out the `.example` on your local project.
Also make sure you have installed in your local machine the correct Java version, in this case as the `jvmTarget ` indicates is version 11.

As a suggestion for handling versions on your local machine you probably want to use some kind of version manager tool such as https://sdkman.io/

Have fun exploring our project! 💖
