### ISSUE TITLE
make bootstrp error

### ISSUE THREAD

**Issue by Coder-DanielHan** [kickstarter/android-oss#17]
bogon:android-oss-master DanielHan$ make bootstrap
git submodule sync --recursive
fatal: Not a git repository (or any of the parent directories): .git
make: *** [submodules] Error 128
bogon:android-oss-master DanielHan$

**Comment by droanmalik** [comment]
I was getting the same error. Downloading the project using `git clone` fixed it

**Comment by Coder-DanielHan** [comment]
@droanmalik I just downloaded the zip

**Comment by mbrandonw** [comment]
@Coder-DanielHan yeah, cloning is necessary since we use submodules for some dependencies. lemme know if that works...

**Comment by Coder-DanielHan** [comment]
which branch should I clone?

**Comment by mbrandonw** [comment]
`master` should be fine. make sure to pull the newest.

**Comment by Coder-DanielHan** [comment]
It's ok.But it stucked at cloning material-design-icons

> bogon:android-oss DanielHan$ make bootstrap
git submodule sync --recursive
Synchronizing submodule url for 'vendor/material-design-icons'
git submodule update --init --recursive || true
Cloning into '/Users/DanielHan/AndroidStudioProjects/android-oss/vendor/material-design-icons'...

**Comment by mbrandonw** [comment]
weird, not sure what is up with [material icons](https://github.com/google/material-design-icons). maybe github was having a bad day? 

gonna close this for now, but let us know if you have more questions!
