### ISSUE TITLE
apply plugin: 'com.android.application' twice

### ISSUE THREAD

**Issue by Jawnnypoo** [kickstarter/android-oss#19]
`apply plugin: 'com.android.application'` is found both at the top and the bottom of the app's `build.gradle`.  Is this intentional, or something being overlooked? Just curious. Happy to make a PR if it is not on purpose 👍

**Comment by luoser** [comment]
good catch! we are in the midst of upgrading everything as needed (seeing as how we're still targeting `23`) so this, as well as many of the upgrade-oriented PR's, will probably be merged in as one general PR on our end to get up to speed

**Comment by rockgecko-development** [comment]
Cheers, I wasn't able to run the unit tests (got a 'no tests found' error) until I removed the second `apply plugin: 'com.android.application' `

**Comment by luoser** [comment]
#29 thanks y'all
