### ISSUE TITLE
To Comment or Not to Comment?

### ISSUE THREAD

**Issue by selmanon** [kickstarter/android-oss#195]
Hello there,

There is an awesome episode that discuss [code health](https://testing.googleblog.com/2017/07/code-health-to-comment-or-not-to-comment.html) published by google folks on their blog : googleblog.com. 

Among the advices : 
> avoid comments that just repeat what the code does.

What I suggest is to apply this advice 👍 

So this code : 
```
interface Inputs {
    /** Call when the project context section is clicked. */
    void projectClicked();

    /** Call when the view messages button is clicked. */
    void viewMessagesButtonClicked();
  }
```

Will become : 
```
interface Inputs {
    void projectClicked();

    void viewMessagesButtonClicked();
  }
```

**Comment by eoji** [comment]
Hi @selmanon,

Per our own documentation [here](https://github.com/kickstarter/native-docs/blob/master/vm-structure.md) , we prefer comments (for now) but thank you for the suggestion!
