### ISSUE TITLE
Can't login with any auth and see any projects.

### ISSUE THREAD

**Issue by fisache** [kickstarter/android-oss#21]
I installed your app according to 'Getting Started'. 
But I can't do anything after showing base activity.
How to solve it?
Thanks.

**Comment by luoser** [comment]
as noted in our Getting Started section,

> Follow these instructions to build and run the project without data; note that the app will be blank.

we have set up the repo so that you can build the project, but without any server data. our future todo is to provide mock server data, so stay tuned

**Comment by fisache** [comment]
Ok, thanks :)
