### ISSUE TITLE
D:\AndroidStudioProjects\android-oss\app\build\intermediates\manifests\full\externalMin21\debug\AndroidManifest.xml

### ISSUE THREAD

**Issue by zhoujingheng** [kickstarter/android-oss#23]
Error:(356, 28) No resource found that matches the given name (at 'value' with value '@string/koala_endpoint').
Error:(356, 28) No resource found that matches the given name (at 'value' with value '@string/koala_endpoint').

**Comment by luoser** [comment]
can you try running `make bootstrap`?

**Comment by zhoujingheng** [comment]
yes,but make not found;my system is windows10.

**Comment by michaldrabik** [comment]
@zhoujingheng Check #7.

**Comment by luoser** [comment]
@michaldrabik thanks for pointing to that issue, was bout to do the same! we'll keep that Windows thread issue open for now to hold the Windows `make` discussions
