### ISSUE TITLE
Status bar overlaps side navigation on the Essential phone

### ISSUE THREAD

**Issue by starkej2** [kickstarter/android-oss#230]
![screenshot_20180326-152005](https://user-images.githubusercontent.com/1320020/37935740-b10a656c-3120-11e8-92ea-80bf48ce4c11.png)

**Comment by starkej2** [comment]
It looks like the layout has `fitsSystemWindows` applied properly, but it doesn't appear to be working properly on the Essential PH-1. Not sure if it's a problem w/ the phone or this app though. 

I tried to fix it by programmatically adding margin/padding equal to the status bar height to the top of the navigation drawer using `systemWindowInsetTop` provided by the `View.setOnApplyWindowInsetsListener`...didn't really help.

**Comment by michaelsam94** [comment]
we can make the status bar transparent and follow material guidelines 
![material](https://user-images.githubusercontent.com/9461037/38063395-3dbe33a6-32f9-11e8-8d83-69ab243a2fb4.JPG)

**Comment by eoji** [comment]
Hey Jeffrey(@starkej2)!! Thanks for the feedback. And thank you @michaelsam94 for the reference! This issue is logged in our roadmap and it will be in an upcoming release 🤓

**Comment by eoji** [comment]
Hey Jeffrey 🤓 I finally got some time to address this. Thanks again for pointing it out!

**Comment by starkej2** [comment]
🎃
