### ISSUE TITLE
New Logo For Kickstarter

### ISSUE THREAD

**Issue by mirzazulfan** [kickstarter/android-oss#237]
Hello.
I wanted to contribute to kickstarter and I designed a logo for kickstarter. If you like it, you can use it. I'll send you files and pr, is there anything you want ? 
![kickstarter](https://user-images.githubusercontent.com/36124339/38463461-a2d96006-3b25-11e8-9296-5839396f2d34.png)

**Comment by justinswart** [comment]
Hey thanks for the contribution! We're happy with our current logo 👍
