### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by selmanon** [kickstarter/android-oss#238]
>Compilation failed; see the compiler error output for details.

```
import com.kickstarter.libs.utils.SocketUtils;
                                 ^
  symbol:   class SocketUtils
  location: package com.kickstarter.libs.utils
1 error
```

**Comment by Yvrabu** [comment]
I have similar problem on mac

File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
/Users/YRB/Desktop/android-oss-master/app/src/externalMin21/debug/google-services.json
/Users/YRB/Desktop/android-oss-master/app/src/debug/externalMin21/google-services.json
/Users/YRB/Desktop/android-oss-master/app/src/externalMin21/google-services.json
/Users/YRB/Desktop/android-oss-master/app/src/debug/google-services.json
/Users/YRB/Desktop/android-oss-master/app/google-services.json

**Comment by eoji** [comment]
Hi @selmanon & @Yvrabu ! You don't have access to all of our dependencies (they are private) so they are missing. 

For the `SocketUtils` error, I'm going to delete that file in https://github.com/kickstarter/android-oss/pull/260 so let me know if you still have errors after it's merged.
