### ISSUE TITLE
can't not find some class

### ISSUE THREAD

**Issue by zhoujingheng** [kickstarter/android-oss#24]
Error:(14, 34) 错误: 找不到符号
符号:   类 Secrets
位置: 程序包 com.kickstarter.libs.utils

Error:(46, 32) 错误: 找不到符号
符号:   类 KSWebViewClient
位置: 程序包 com.kickstarter.services
Error:(71, 103) 错误: 程序包KSWebViewClient不存在

**Comment by MinaSamy** [comment]
Yes, I have the same problem, for example the **KSWebViewClient.java** file is included in the android-**oss/config** directory but it's not loaded in Android Studio

**Comment by LeoHeo** [comment]
I founded solution

1. go to git Clone root directory
2. command `make`

**Comment by luoser** [comment]
@zhoujingheng did @LeoHeo 's steps work for you?

**Comment by zhoujingheng** [comment]
@luoser NO,Windows no command make.

**Comment by luoser** [comment]
@zhoujingheng ah, our team doesn't develop on Windows so we have been lacking in Windows support. please see https://github.com/kickstarter/android-oss/issues/16 for some guidance

**Comment by Pingsh** [comment]
解决这个问题了, 直接找到 "Secret.java.example" 文件, 重命名为 "Secret.java" ,重新 build 一下, 就可以运行了 @zhoujingheng
