### ISSUE TITLE
Question: how are secrets handled in android-oss?

### ISSUE THREAD

**Issue by bootstraponline** [kickstarter/android-oss#251]
I'm interested to learn how secrets are handled in the Android oss repo. There are usually API keys and other credentials required to build the app that shouldn't be open sourced. I think Kickstarter is using a git submodule?

I'd like to replicate a similar setup for my apps. Any details would be appreciated.

**Comment by eoji** [comment]
Hello @bootstraponline we are! If you take a look at https://github.com/kickstarter/android-oss/blob/master/Makefile you can see where we copy over our dependencies.

**Comment by bootstraponline** [comment]
Thanks!
