### ISSUE TITLE
Content is empty

### ISSUE THREAD

**Issue by idcmsbeta** [kickstarter/android-oss#252]
I have install it to the phone.. 

From android catlog see  like this

> 05-19 23:24:32.341 16936-16986/com.kickstarter.kickstarter.debug V/MixpanelAPI.DChecker: Querying decide server, urls:
>         >> https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=5df63f94-9e5e-4a0e-ba1f-7352c250e3e4
> 05-19 23:24:32.341 16936-16986/com.kickstarter.kickstarter.debug V/MixpanelAPI.Message: ConnectivityManager says we are online
>     Attempting request to https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=5df63f94-9e5e-4a0e-ba1f-7352c250e3e4
> 05-19 23:24:33.243 16936-16986/com.kickstarter.kickstarter.debug V/MixpanelAPI.DChecker: Cannot get https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=5df63f94-9e5e-4a0e-ba1f-7352c250e3e4, file not found.
>     java.io.FileNotFoundException: https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=5df63f94-9e5e-4a0e-ba1f-7352c250e3e4
>         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)

**Comment by eoji** [comment]
Hello! I'm not sure I understand, what is the question?

**Comment by idcmsbeta** [comment]
The left side menu blank, the content of each tab is empty.

**Comment by eoji** [comment]
Hi @idcmsbeta! You don't have access to all of our dependencies (they are private) so that's why the content is empty.

**Comment by idcmsbeta** [comment]
Wait .better private this project if status failure @eoji
