### ISSUE TITLE
can not find @string/koala_endpoint

### ISSUE THREAD

**Issue by aigeek** [kickstarter/android-oss#26]
Error:(356, 28) No resource found that matches the given name (at 'value' with value '@string/koala_endpoint').

**Comment by mbrandonw** [comment]
Hi! Did you run `make bootstrap` before building?

**Comment by aigeek** [comment]
1.download the project
2.make bootstrap
3.open it with android studio.
It's my fault that I did 2 before 3..
Thank you.
But there is no data from server..It's not very convenient.

**Comment by luoser** [comment]
@aigeek yeah, the oss app will not get any data from the server, but we are going to provide mock data at some point so stay posted!

**Comment by malaki12003** [comment]
How can I make on windows?
