### ISSUE TITLE
"token, no project found"

### ISSUE THREAD

**Issue by rj12info** [kickstarter/android-oss#265]
Launch app from Android Studio on an Emulator
Able to see tabs and navigation drawer in app

https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=0b07c7b2-531c-4cf9-9ef4-4f473f57467e

**Comment by eoji** [comment]
Hi @rj12info, what's the issue you're seeing? We don't use Mixpanel as a service so that error is accurate.

**Comment by rj12info** [comment]
unable to see ui in emulator
1st tab
![screenshot_1530192423](https://user-images.githubusercontent.com/6755892/42036522-5e9d8566-7b03-11e8-9adf-2624cdccfc02.png)

All other tabs show empty except for 1st tab

![screenshot_1530192340](https://user-images.githubusercontent.com/6755892/42036475-4266d5be-7b03-11e8-85da-b5deac666daf.png)

**Comment by eoji** [comment]
Hi @rj12info, as mentioned in our README: 

> Follow these instructions to build and run the project without data; note that the app will be blank.

> We intend for this project to be an educational resource: we are excited to share our wins, mistakes, and methodology of Android development as we work in the open. Our primary focus is to continue improving the app for our users in line with our roadmap.

Currently, it's not possible for external contributors to see production data but it's something we are considering implementing in the future.

**Comment by eoji** [comment]
Hi @rj12info,

![image](https://user-images.githubusercontent.com/1289295/45316559-67753a80-b505-11e8-98e1-cfab23838897.png)

We merged in #324 that allows OSS contributors to see mock data so the app is no longer blank.
