### ISSUE TITLE
Is there an option to have mock data like the iOS app?

### ISSUE THREAD

**Issue by itayvallach** [kickstarter/android-oss#280]

**Comment by selmanon** [comment]
Do you mean that you could run the iOS app ?

Le jeu. 26 juil. 2018 09:48, Itay Vallach <notifications@github.com> a
écrit :

**Comment by itayvallach** [comment]
No. On Android, the app is blank, no data at all, I cannot make any use of it. I mean to have an option like the iOS app has, to mock hardcoded data. This is from your iOS documentation:
* To provide a mock version that serves up hard-coded data immediately, set KsApi.Secrets.isOSS = true.

**Comment by eoji** [comment]
HI @itayvallach and @selmanon! From January until June, it was just me managing this repo on my own 😅 But now there are 2 engineers 🤓🤓And we have added creating mock data to our Android Engineering roadmap so the repo can be more helpful to people outside of our organization. I'm hoping to start this work in Q3.

**Comment by eoji** [comment]
Hi @itayvallach and @selmanon 

![image](https://user-images.githubusercontent.com/1289295/45316559-67753a80-b505-11e8-98e1-cfab23838897.png)

We merged in #324 that allows OSS contributors to see mock data so the app is no longer blank.
