### ISSUE TITLE
when i login or logout ,how can i change the CurrentUserType in Environment....

### ISSUE THREAD

**Issue by liuruimilk** [kickstarter/android-oss#290]
forgive my Chinglish
first time to start the app. there is no user info....so , in ApplicationModule provideCurrentUserType is null, but   okhttp is building...... when i logined ,then the app got the user info.....but i cant find anywhere code to refresh the global ApplicationComponent....so , the ApplicationComponent provide's
Environment always have the old CurrentUserType...

**Comment by eoji** [comment]
Hi @liuruimilk, if I understand correctly, no data is loading? That's expected behavior. As mentioned in our README:

>Follow these instructions to build and run the project without data; note that the app will be blank.

>We intend for this project to be an educational resource: we are excited to share our wins, mistakes, and methodology of Android development as we work in the open. Our primary focus is to continue improving the app for our users in line with our roadmap.

We do have plans to create some mock data so that playing with the app will be a more interactive experience.

**Comment by liuruimilk** [comment]
@eoji Hi,you replied to the wrong person

**Comment by eoji** [comment]
Hi @liuruimilk,

![image](https://user-images.githubusercontent.com/1289295/45316559-67753a80-b505-11e8-98e1-cfab23838897.png)

We merged in #324 that allows OSS contributors to see mock data so the app is no longer blank.
