### ISSUE TITLE
can't run app with Crashlytics found an invalid API key: null.

### ISSUE THREAD

**Issue by dwkim891220** [kickstarter/android-oss#294]
hello!
want build and run application in my phone.
did make bootstrap and run.
but can't run with below message

Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.

please help me thanks!

**Comment by eoji** [comment]
Hi @dwkim891220! We think we fixed the issue in #299. Please let us know if you are still having issues.
