### ISSUE TITLE
Unable to run ./script/bootstrap - Function Not Found

### ISSUE THREAD

**Issue by timkaboya** [kickstarter/android-oss#30]
So I encountered #16 but on manually doing the file commands, that seemed to fix it.  
Now this script `./script/bootstrap` is giving this error. 

```
./script/bootstrap
./script/bootstrap: 3: ./script/bootstrap: function: not found

./script/bootstrap: 6: ./script/bootstrap: Syntax error: "}" unexpected
Makefile:2: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2
```
It seems as tho its failing on function "say" in the script. Whats that function for? 

@Kickstarter This code you threw up online is not running...

**Comment by LetItRock** [comment]
@timkaboya did you tried to run app without this bootstrap?

**Comment by hodannyy** [comment]
@timkaboya I ran into the same issue and have a fix. Check out my pull request #43.

**Comment by rome753** [comment]
on my Ubuntu 16, edit the ./script/bootstrap file with a text editor,
change "function say {..." to "say() {...",
and also "function loudspeaker {..." to "loudspeaker() {...",
then apt install ruby and curl,
then ok.

**Comment by luoser** [comment]
closing now as @hodanny 's fix has been merged.
