### ISSUE TITLE
Error:Execution failed for task ':app:processExternalMin21DebugGoogleServices'. > No matching client found for package name 'com.kickstarter.kickstarter.debug'

### ISSUE THREAD

**Issue by liuruimilk** [kickstarter/android-oss#32]
when i build the app, get a error ->
Error:Execution failed for task ':app:processExternalMin21DebugGoogleServices'.
> No matching client found for package name 'com.kickstarter.kickstarter.debug'

how can i fix the problem?

**Comment by luoser** [comment]
ah. for now go to `View > Tool windows > Build variants` and switch the build variant to anything ending in `Release`.  the package name in the `google-services.json` we're copying over only matches `com.kickstarter.kickstarter` release names so looks like that prevents compiling.

will work on a fix for this asap

**Comment by luoser** [comment]
@liuruimilk this should be fixed now for all build variants. can you please try pulling master, running `make bootstrap` then building the project again? thanks!

**Comment by liuruimilk** [comment]
@luoser thank you.it's works now.but ,i want to install the app to see the effect.there is no release.keystore. so,how to run the app without no debug and no release.keystore.
forgive my Chinglish.

**Comment by liuruimilk** [comment]
@luoser that's ok,i have downloaded apk,thanks.

**Comment by liuruimilk** [comment]
it works,thank you.

**Comment by kingfaisalict** [comment]
when i build the app, get a error ::::::    No matching client found for package name 'com.kickstarter.kickstarter.debug'

Please, explain how can i fix it.

I am a novice

**Comment by narayananiyer86** [comment]
I'm getting the same issue

**Comment by SeanFelipe** [comment]
getting this again now. Worked previously but now the build is failing. `make bootstrap` doesn't seem to resolve things ... it was working about a month ago for me.

**Comment by eoji** [comment]
@SeanFelipe That's weird but I'm glad it's fixed. Feel free to open a new issue because @luoser had to ping me about this one since I wasn't at Kickstarter in 2016 🙂
