### ISSUE TITLE
google-services.json  is missing

### ISSUE THREAD

**Issue by ashokbg** [kickstarter/android-oss#33]
because  of not having google-services.json i am getting error what to do for that

**Comment by luoser** [comment]
can you try running `make bootstrap`? we've updated the `Makefile` recently

**Comment by ashokbg** [comment]
recently updated Makefile  only i am using then also still same issue.

**Comment by luoser** [comment]
can you please pull the latest `master`, try `make bootstrap` again, then build the project in android studio? the gradle process should be generating the appropriate `google-services.json` file for you

**Comment by ashokbg** [comment]
pulled recent code. and also checked with different build  variants getting same error: 
Error:Execution failed for task ':app:processInternalPre21ReleaseGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  F:\android-oss\app\src\internalPre21\release\google-services.json
  F:\android-oss\app\src\release\internalPre21\google-services.json
  F:\android-oss\app\src\internalPre21\google-services.json
  F:\android-oss\app\src\release\google-services.json
  F:\android-oss\app\google-services.json

**Comment by ashokbg** [comment]
its my mistake..
