### ISSUE TITLE
BUILD_DATE dynamic field causes slower builds

### ISSUE THREAD

**Issue by tasomaniac** [kickstarter/android-oss#34]
`BUILD_DATE` is dynamically created out of current date. It includes seconds as well. 
This means that every time someone builds, `BuildConfig` class changes. That causes java compilation. 

This is not necessary while running tests and changing only xml layouts. In those cases, the builds can be faster. 

To prevent it, you can persist the date (and even git-sha) inside a file in `build` folder. And project clean will create the right ones.

Here I have an example implementation: 
https://github.com/gdg-x/frisbee/blob/develop/app/build.gradle#L206

**Comment by luoser** [comment]
thanks for this suggestion! sorry it took so long to address, but thank you for sharing your implementation and if you'd like to see we are working in that solution to our codebase here! #92

**Comment by luoser** [comment]
closing as we have merged the change, thanks again!
