### ISSUE TITLE
Some enhancement ideas

### ISSUE THREAD

**Issue by naufaladi** [kickstarter/android-oss#346]
Hello, I would like to point out some feature enhancement idea that might actually be useful, here they are:

1.	Interface overhaul on home project listing to be more compact and simple.
The current “home” project list interface only shows a little portion of the project’s description in the project overview. It also leaves a lot of wasted blank space, which I would like to improve to make the interface a bit more compact.

2.	Interface overhaul on search project listing to list out more details.
Project overview in search session leaves some crucial information such as the number of backers, and also it has a tiny thumbnail. The size is a problem because the thumbnail was designed with a desktop monitor size in mind, so making it more tiny than usual is not a wise choice in my opinion. I would like to improve this by listing a few more project details and a bigger thumbnail so the user can more easily see it. 

3.	Adds search result counter (for example, “549 results were found”) in the search listing.
This is straightforward, I think it would be a nice improvement to let the user know how many results/projects were found with the keyword.

4.	Adds tagging/filtering in the search listing. (for example, list only projects with “board game” tag.)
This might be the most important, this app still does not have a filtering search result feature.

5.	Adds number counter in project listing (#1, #2, #3, etc.)
A nice addition since there are so many projects being listed that user might want to keep track of where they are.

These ideas might already be around for a while but I'd only wanted to point it out again, thanks for reading this!

**Comment by eoji** [comment]
Hi @naufaladi,

Thanks for this thoughtful feedback! These are all great ideas we have considered and discussed with the design and product team. 

There are currently only 2 maintainers of this repo, myself and @Rcureton, and we are trying to strike a balance between maintenance, bugs, and new features. Going forward, for product feedback, you can send an email to android@kickstarter.com. Those messages get seen by me, the Product Manager, and the Community Support team.

Thank you for your interest and support of the Kickstarter Android app!
Izzy
