### ISSUE TITLE
Error:Execution failed for task ':app:processExternalMin21DebugGoogleServices'. > File google-services.json is missing. The Google Services Plugin cannot function without it.  

### ISSUE THREAD

**Issue by YadoEmoji** [kickstarter/android-oss#36]
Error:Execution failed for task ':app:processExternalMin21DebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  F:\android\android-oss-master\app\src\externalMin21\debug\google-services.json
  F:\android\android-oss-master\app\src\debug\externalMin21\google-services.json
  F:\android\android-oss-master\app\src\externalMin21\google-services.json
  F:\android\android-oss-master\app\src\debug\google-services.json
  F:\android\android-oss-master\app\google-services.json

**Comment by liuruimilk** [comment]
do not download zip just clone, run make bootstrap.and then,you'll find another problem what the same with me.

**Comment by luoser** [comment]
@YadoEmoji please let us know if @liuruimilk 's instructions work for you

**Comment by ababavali23** [comment]
Still i am facing same issue

**Comment by farmazon3000** [comment]
How are you "building the app"?

**Comment by dancrisan** [comment]
I have the same issue, can we go through a step by step process of how are you "building" the app?

**Comment by dancrisan** [comment]
Ok so issue solved: if you download as a zip, make sure you have git installed and once in the project directory, you can just do "git init" and then "make bootrap". Then close android studio if it's open, then you can open the project again and run it normally.

**Comment by dancrisan** [comment]
If you didn't donwload as a zip, make sure you run "make bootstrap" before opening the app within android studio.

**Comment by BigKarel** [comment]
@dancrisan misspell: make boostrap

**Comment by jorgecasariego** [comment]
Thanks @dancrisan 

"make bootstrap" was the solution! 😃

**Comment by BishoyAbd** [comment]
I have the same problem, yet I could not get what is "make bootstrap" ?
what does that mean ?

**Comment by lalitsharmaking** [comment]
> Ok so issue solved: if you download as a zip, make sure you have git installed and once in the project directory, you can just do "git init" and then "make bootrap". Then close android studio if it's open, then you can open the project again and run it normally. 

How the actual hell we do this ? How to make bootstrap what is the code can u help man ? I m tired really
