### ISSUE TITLE
Process 'command '   .../Kickstarter/android-oss/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by luckyAF** [kickstarter/android-oss#371]
when I build the project, I get following error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installApolloCodegen'.
> Process 'command '/Users/xiangzhongfei/Documents/work/OpenDemo/Kickstarter/android-oss/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1


```

**Comment by eoji** [comment]
Hi @luckyAF, I'm not sure if this is a Kickstarter app specific issue. I bumped Apollo yesterday in #394 and can still build successfully. This seems like a node/npm issue. I believe that's what [https://github.com/apollographql/apollo-android](Apollo) uses under the hood. What do you get when you do `node -v` in your terminal?

**Comment by luckyAF** [comment]
v6.11.3

**Comment by eoji** [comment]
Hi @luckyAF,

Thanks! I did some googling and saw that this is definitely an Apollo issue and not a Kickstarter issue. I think this comment is helpful:

https://github.com/apollographql/apollo-android/issues/608#issuecomment-369899779

I would open an issue here if you're still running into problems: https://github.com/apollographql/apollo-android/issues

Best,
Izzy
