### ISSUE TITLE
repository 'https://github.com/kickstarter/native-secrets/' not found

### ISSUE THREAD

**Issue by narakai** [kickstarter/android-oss#41]
I have encountered issue as below, please kindly advise:

git clone https://github.com/kickstarter/native-secrets vendor/native-secrets
Cloning into 'vendor/native-secrets'...
remote: Repository not found.
fatal: repository 'https://github.com/kickstarter/native-secrets/' not found

**Comment by mbrandonw** [comment]
We should do a better job of suppressing that error message, but it shouldn't cause you any problems. The project should build without access to that private repo. Can you give it a shot?

**Comment by narakai** [comment]
Build successfully this time. I have changed some gradle setting and the build failure was caused by this mistake. Thanks for the advice.
