### ISSUE TITLE
Getting error on "make bootstrap"

### ISSUE THREAD

**Issue by amitsri20** [kickstarter/android-oss#47]
Getting below error on "make bootstrap":

`git submodule sync --recursive
Synchronizing submodule url for 'vendor/material-design-icons'
git submodule update --init --recursive || true
git submodule foreach git checkout
Entering 'vendor/material-design-icons'
# Copy java secrets over. Fallback to example secrets if they don't exist.
(Skipping secrets.)
cp vendor/native-secrets/android/Secrets.java app/src/main/java/com/kickstarter/libs/utils/Secrets.java \
                || cp app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example app/src/main/java/com/kickstarter/libs/utils/Secrets.java
cp: cannot stat ‘vendor/native-secrets/android/Secrets.java’: No such file or directory
cp vendor/native-secrets/ruby/secrets.rb lib/milkrun/secrets.rb || true
cp: cannot stat ‘vendor/native-secrets/ruby/secrets.rb’: No such file or directory
cp vendor/native-secrets/fonts/ss-kickstarter.otf app/src/main/assets/fonts/ss-kickstarter.otf || true
cp: cannot stat ‘vendor/native-secrets/fonts/ss-kickstarter.otf’: No such file or directory
# Copy kola configs over. Fallback to examples if they don't exist.
mkdir -p app/src/debug/res/values/
mkdir -p app/src/main/res/values/
cp vendor/native-secrets/android/koala_endpoint_debug.xml app/src/debug/res/values/koala_endpoint.xml \
                || cp config/koala_endpoint.xml.example app/src/debug/res/values/koala_endpoint.xml
cp: cannot stat ‘vendor/native-secrets/android/koala_endpoint_debug.xml’: No such file or directory
cp vendor/native-secrets/android/koala_endpoint.xml app/src/main/res/values/koala_endpoint.xml \
                || cp config/koala_endpoint.xml.example app/src/main/res/values/koala_endpoint.xml
cp: cannot stat ‘vendor/native-secrets/android/koala_endpoint.xml’: No such file or directory
# Copy web client over.
cp -rf vendor/native-secrets/android/WebViewJavascriptInterface.java app/src/main/java/com/kickstarter/libs/WebViewJavascriptInterface.java \
                || cp -rf config/WebViewJavascriptInterface.java app/src/main/java/com/kickstarter/libs/WebViewJavascriptInterface.java
cp: cannot stat ‘vendor/native-secrets/android/WebViewJavascriptInterface.java’: No such file or directory
cp -rf vendor/native-secrets/android/KSWebViewClient.java app/src/main/java/com/kickstarter/services/KSWebViewClient.java \
                || cp -rf config/KSWebViewClient.java app/src/main/java/com/kickstarter/services/KSWebViewClient.java
cp: cannot stat ‘vendor/native-secrets/android/KSWebViewClient.java’: No such file or directory
mkdir -p app/src/main/assets/www/
cp vendor/native-secrets/android/WebViewJavascript.html app/src/main/assets/www/WebViewJavascript.html || true
cp: cannot stat ‘vendor/native-secrets/android/WebViewJavascript.html’: No such file or directory
./script/bootstrap
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
find: warning: you have specified the -depth option after a non-option argument -name, but options are not positional (-depth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: paths must precede expression: 1
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
E:\android\examples\android-oss\script\bootstrap: line 28: bundle: command not found
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
cp: cannot stat ‘vendor/native-secrets/android/externalMin21Debug/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/externalPre21Debug/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/externalMin21Release/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/externalPre21Release/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/internalMin21Debug/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/internalPre21Debug/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/internalMin21Release/google-services.json’: No such file or directory
cp: cannot stat ‘vendor/native-secrets/android/internalPre21Release/google-services.json’: No such file or directory
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
mv: cannot move ‘/tmp/pidcat’ to ‘/usr/local/bin/pidcat’: No such file or directory
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
E:\android\examples\android-oss\script\bootstrap: line 5: ruby: command not found
make: *** [bootstrap] Error 127
`

**Comment by mbrandonw** [comment]
Our bootstrap is pretty tightly coupled to the way we work as a team, which means it mostly only supports macOS and requires some things to be installed first like ruby. We don't have any plans to make a more universal bootstrap, so it might require you to perform some of the steps manually in a console.

Sorry about that!

Gonna close for now, but let us know you have more questions...

**Comment by sunardo** [comment]
I have some problem... still  can't solve it.
Wonder if @amitsri20 have solution.
