### ISSUE TITLE
Unable to get FacebookContentProvider

### ISSUE THREAD

**Issue by dancrisan** [kickstarter/android-oss#49]
Hey, I get this error as soon as i try to run the app :  java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/data/app/com.kickstarter.kickstarter.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kickstarter.kickstarter.debug-1/lib/x86_64, /system/lib64, /vendor/lib64]]

I just pulled, ran "make bootstrap" and with Android Studio, simply trying running the application.

**Comment by luoser** [comment]
hm. if you downloaded the repo can you please try cloning it instead and running `make bootstrap` again?

**Comment by luoser** [comment]
Going to close this now due to inactivity
