### ISSUE TITLE
com.kickstarter.extensions.showSnackBar

### ISSUE THREAD

**Issue by sbenitez10** [kickstarter/android-oss#521]
When i was trying to debugging the code to understand it  i got a error. looking to the classes i found that you have a un resolve reference that is com.kickstarter.extensions.showSnackBar

![image](https://user-images.githubusercontent.com/35940950/57036213-3921a800-6c19-11e9-9b38-8a1027922b61.png)

**Comment by eoji** [comment]
Hey @sbenitez10, I'm not getting this error. Have you been successfully able to build the app previously? 

<img width="602" alt="Screen Shot 2019-05-01 at 3 00 09 PM" src="https://user-images.githubusercontent.com/1289295/57036305-eac4d700-6c21-11e9-9cbe-d0486c398ed4.png">

**Comment by sbenitez10** [comment]
nope i wasnt.  i am checking it know

**Comment by sbenitez10** [comment]
HI, i was trying to build the app but i  get this error and i dont know how to solve it 
![image](https://user-images.githubusercontent.com/35940950/57048856-55364100-6c3b-11e9-99a3-d97ca3ca64cd.png)

**Comment by eoji** [comment]
I think that error is a red herring. When you open the project, Android Studio makes suggestions about updating your version of kotlin and gradle but that actually breaks the app. Try reverting your changes in `build.gradle` and `gradle-wrapper properties` and then rebuild. Tell me how it goes.

**Comment by sbenitez10** [comment]
i revert my changes but nothings happens i still getting the same error

![image](https://user-images.githubusercontent.com/35940950/57089147-66c62a00-6cc9-11e9-8b40-1480a519b0c0.png)

![image](https://user-images.githubusercontent.com/35940950/57089217-8cebca00-6cc9-11e9-9700-3d7e95cdc4c5.png)

sorry for the problems.

**Comment by eoji** [comment]
No problem! Looks like the build `"completed successfully"` and that error shouldn't affect you so have you tried actually running it on a device or emulator?

Here's my output when I build the app:
<img width="662" alt="Screen Shot 2019-05-02 at 12 45 23 PM" src="https://user-images.githubusercontent.com/1289295/57092058-8a44a100-6cd8-11e9-8fe5-5ae63186c151.png">

**Comment by sbenitez10** [comment]
yeap i run it but when i scroll too much the first view it generates a ANR. so i thought that maybe was because the build had that error.

**Comment by eoji** [comment]
Alright, I just pulled down the OSS version and debugged 🕵🏾‍♀️. I will open a PR to fix this!

**Comment by eoji** [comment]
The PR has been merged. Please pull the latest and you shouldn't see the crash anymore!
