### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by narayananiyer86** [kickstarter/android-oss#616]
I'm getting the error while building gradle. Here is the error

com.apollographql.apollo.compiler.parser.GraphQLDocumentParseException:
Failed to parse GraphQL file C:\Users\Narayanan KA\Downloads\Android projects\Kickstarter\app\src\main\graphql\activity.graphql (2:35)
Unsupported token }

**Comment by eoji** [comment]
Hey @narayananiyer86, I'm able to build the OSS app. Could you paste what your `activity.graphql` looks like?

**Comment by narayananiyer86** [comment]
Hello ,



This is what my activity.graphql looks like.



mutation ClearUserUnseenActivity {
  clearUserUnseenActivity(input: {}) {
      activityIndicatorCount
  }
 }


Regards ,
K.A. Narayanan




________________________________

**Comment by eoji** [comment]
Hmm mine is identical and I'm able to run the project. You've tried cleaning and rebuilding, right? Apollo needs a rebuild to autogenerate the classes. I saw your comment here: https://github.com/apollographql/apollo-android/issues/1545#issuecomment-533814345

I'd make sure you're on the latest from master, run `make bootstrap`, and lemme know how it goes!

**Comment by eoji** [comment]
Hey @narayananiyer86 I just bumped the version of Apollo we use in #618 so you should pull and try rebuilding! Please reopen if you still have issues.
