### ISSUE TITLE
Windows can't run make

### ISSUE THREAD

**Issue by ren545457803** [kickstarter/android-oss#7]
don't have command 'run'

**Comment by luoser** [comment]
ah yes. unfortunately we don't use Windows for development on our team so we can definitely use some suggestions on how we can improve on that front!

**Comment by AuspeXeu** [comment]
I am currently using Bash on Ubuntu on Windows for these purposes

https://msdn.microsoft.com/en-gb/commandline/wsl/about

**Comment by ren545457803** [comment]
@AuspeXeu Thanks

**Comment by ashishbhandari** [comment]
good to install cygwin on windows and run that command.. :)

**Comment by Qamar4P** [comment]
This work for me. Run
**D:\CodeLab\Android-oss>**`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake" bootstrap`

**Comment by Qamar4P** [comment]
Hey guys thanks to @LetItRock
1. Did copy and rename files manually refered in Makefile eg. "mkdir(Create directory) -p app/src/debug/res/values and  cp (Copy) app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example app/src/main/java/com/kickstarter/libs/utils/Secrets.java
2. Run Window Bash (in my case Git Bash) as administrator and run ./script/bootstrap

Then build project works in Window.

**Comment by mbrandonw** [comment]
Thanks for the tips for getting things to work in windows! Gonna close this for now, but will use this as a reference for when the issue comes up again!
