### ISSUE TITLE
[Feature Request] Add "Sign in with Google Account" option

### ISSUE THREAD

**Issue by Donboscow** [kickstarter/android-oss#701]
Please kindly add "Sign in with Google Account" option so that we can seamlessly log in kickstarter from all platform.

**Comment by eoji** [comment]
Hi @Donboscow,

Thanks for checking out our open source repos and for the suggestion! I'll pass this along to our product team.

Github issues are usually opened for code related questions. We have 2 email addresses for app feedback; android@kickstarter.com and app@kickstarter.com, for Android and iOS respectively. Going forward, please try to use one of those emails for feature requests.

Best,
Izzy
