### ISSUE TITLE
Double Bracket initialization is bad.

### ISSUE THREAD

**Issue by Singwai** [kickstarter/android-oss#74]
hello,

I see that the app occasionally uses double bracket initialization. For example here
https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/libs/KSString.java#L26-L30

and 

https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/libs/KSString.java#L74-L81

This should be absolutely avoided IMO. The reason is that each of them will create an inner anonymous class and they can be easily avoided.

Here is an example.

Complied using JDK 1.8.0_45

```
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;


public class DoubleBracket {

    public static void main(String[] args) {
        Map<String, String> lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());

        lazy = new HashMap<String, String >() {{
            put("a", "b");
            put("1", "2");

        }};
        System.out.println(lazy.toString());
    }
}
```

![image](https://cloud.githubusercontent.com/assets/5863227/24270836/1d004b98-0fed-11e7-8bb7-461bd2203dbf.png)

Here is what we see in the APK explore
![image](https://cloud.githubusercontent.com/assets/5863227/24271366/4cdd668c-0fef-11e7-972f-97f8a0d0ab80.png)

Let me know what you think.

**Comment by luoser** [comment]
heya, good suggestion. i think we use {{}} in just a few places so didn't analyze the complexity too much when building the app, but we're totally up for removing them. if you'd like, feel free to open a PR and we'll merge, or likely we'll table this task for later, prioritizing feature development

**Comment by Singwai** [comment]
kk I will work on it
