### ISSUE TITLE
Add products and listings?

### ISSUE THREAD

**Issue by rocks860** [kickstarter/android-oss#746]
Sorry if I sound ignorant, is there a way to add categories and add listings or this project has a different meaning? Is this like an ecommerce app?  I did try to read more about it, but couldn't find what it does.
Thanks for your time

**Comment by eoji** [comment]
Hi @rocks860!

 If you're not sure what Kickstarter is, take a look at our [Help Center](https://help.kickstarter.com/hc/en-us).

If you're not what this repository is about, check out our [README](https://github.com/kickstarter/android-oss/blob/master/README.md)
