### ISSUE TITLE
Android Studio can't find fabric.properties file

### ISSUE THREAD

**Issue by Grandolf49** [kickstarter/android-oss#808]
**Issue**

- I forked the repository, cloned into a local directory and imported the project in Android Studio 3.6.1
- While importing, Android Studio throws an error:
```
Caused by: java.io.FileNotFoundException: C:\Users\chinm\Desktop\Open Source\Kickstarter\android-oss\app\fabric.properties (The system cannot find the file specified)
```

**Comment by eoji** [comment]
Hi @Grandolf49, thanks for checking out the repo! 

That's expected because it sounds like you haven't run `make bootstrap` in step 4 of the [README](https://github.com/kickstarter/android-oss#getting-started). Let me know if you're still running into issues after!
