### ISSUE TITLE
[Feature Request] Darkmode

### ISSUE THREAD

**Issue by Zenahr** [kickstarter/android-oss#841]
Is the darkmode feature planned yet? It's a standard that users demand nowadays.

**Comment by Zenahr** [comment]
Here are some preliminary mockups I made on-the-fly. I would be happy to supply the code as well of course (make a pull-request). I can't say how long it'll take me since I haven't looked at the source-code yet.

![comparison-1](https://user-images.githubusercontent.com/47085752/79814860-90b3a900-837f-11ea-8167-d53389a02c0d.png)
![mock-1](https://user-images.githubusercontent.com/47085752/79814863-914c3f80-837f-11ea-8f09-9903058af704.png)

**Comment by eoji** [comment]
Hi @Zenahr,

Thanks for checking out our open source repo and for the suggestion! I'll pass this along to our design team.

We have 2 email addresses for app feedback; android@kickstarter.com and app@kickstarter.com, for Android and iOS respectively. Going forward, please try to use one of those emails for feature requests.

Best,
Izzy

**Comment by Zenahr** [comment]
I opened an issue on github instead since I would be open to contribute to this feature by creating pull requests. Just for clarification: Is this repo open-source and open-contribution or just open-source?

Cheers,
Zenahr

**Comment by eoji** [comment]
Hi @Zenahr,

That's a great question! In the README, we say:
> We intend for this project to be an educational resource: we are excited to share our wins, mistakes, and methodology of Android development as we work in the open. Our primary focus is to continue improving the app for our users in line with our roadmap.

We have had contributions that like #177 and #182 that were really helpful and much needed refactors inline with the roadmap! Dark mode is not currently on the immediate roadmap but when it is, we will update this issue to show you the updated designs if you'd still like to work on them.

Best,
Izzy
