### ISSUE TITLE
missing A Firebase API key

### ISSUE THREAD

**Issue by tonptit** [kickstarter/android-oss#893]
how to fix this crash
Caused by: java.lang.IllegalArgumentException: Please set a valid API key. A Firebase API key is required to communicate with Firebase server APIs: It authenticates your project with Google.

**Comment by emreakcan** [comment]
Hey, you can't run the project directly. There is lots of keys and secrets in this project, you can create your own firebase project and put your api keys. But as I remember if you go through setup process "make bootstrap" does that for you but I'm not sure.

**Comment by emreakcan** [comment]
@JadeByfield89 could you please close that issue?

**Comment by NurseyitTursunkulov** [comment]
> Hey, you can't run the project directly. There is lots of keys and secrets in this project, you can create your own firebase project and put your api keys. But as I remember if you go through setup process "make bootstrap" does that for you but I'm not sure.

does not work

**Comment by NurseyitTursunkulov** [comment]
cp: cannot stat 'vendor/native-secrets/android/Secrets.java': No such file or directory
cp vendor/native-secrets/ruby/secrets.rb lib/milkrun/secrets.rb || true
cp: cannot stat 'vendor/native-secrets/ruby/secrets.rb': No such file or directory
cp vendor/native-secrets/fonts/ss-kickstarter.otf app/src/main/assets/fonts/ss-kickstarter.otf || true
cp: cannot stat 'vendor/native-secrets/fonts/ss-kickstarter.otf': No such file or directory
cp vendor/native-secrets/android/fabric.properties app/fabric.properties || cp config/fabric.properties.example app/fabric.properties
cp: cannot stat 'vendor/native-secrets/android/fabric.properties': No such file or directory
cp vendor/native-secrets/android/slack.properties app/slack.properties || true
cp: cannot stat 'vendor/native-secrets/android/slack.properties': No such file or directory
cp vendor/native-secrets/android/firebase.properties app/firebase.properties || cp config/firebase.properties.example app/firebase.properties
cp: cannot stat 'vendor/native-secrets/android/firebase.properties': No such file or directory
# Copy web client over.
cp -rf vendor/native-secrets/android/WebViewJavascriptInterface.java app/src/main/java/com/kickstarter/libs/WebViewJavascriptInterface.java \
        || cp -rf config/WebViewJavascriptInterface.java app/src/main/java/com/kickstarter/libs/WebViewJavascriptInterface.java
cp: cannot stat 'vendor/native-secrets/android/WebViewJavascriptInterface.java': No such file or directory
cp -rf vendor/native-secrets/android/KSWebViewClient.java app/src/main/java/com/kickstarter/services/KSWebViewClient.java \
        || cp -rf config/KSWebViewClient.java app/src/main/java/com/kickstarter/services/KSWebViewClient.java
cp: cannot stat 'vendor/native-secrets/android/KSWebViewClient.java': No such file or directory
mkdir -p app/src/main/assets/www/
cp vendor/native-secrets/android/WebViewJavascript.html app/src/main/assets/www/WebViewJavascript.html || true
cp: cannot stat 'vendor/native-secrets/android/WebViewJavascript.html': No such file or directory
./script/bootstrap
./script/bootstrap: 5: ./script/bootstrap: ruby: not found
find: warning: you have specified the -depth option after a non-option argument -name, but options are not positional (-depth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: paths must precede expression: `1'
./script/bootstrap: 5: ./script/bootstrap: ruby: not found
./script/bootstrap: 28: ./script/bootstrap: bundle: not found
./script/bootstrap: 5: ./script/bootstrap: ruby: not found
cp: cannot stat 'vendor/native-secrets/android/externalDebug/google-services.json': No such file or directory
cp: cannot stat 'vendor/native-secrets/android/externalRelease/google-services.json': No such file or directory
cp: cannot stat 'vendor/native-secrets/android/internalDebug/google-services.json': No such file or directory
cp: cannot stat 'vendor/native-secrets/android/internalRelease/google-services.json': No such file or directory
cp: cannot stat 'vendor/native-secrets/android/regressionDebug/google-services.json': No such file or directory
cp: cannot stat 'vendor/native-secrets/android/regressionRelease/google-services.json': No such file or directory
./script/bootstrap: 5: ./script/bootstrap: ruby: not found
./script/bootstrap: 5: ./script/bootstrap: ruby: not found
./script/bootstrap: 5: ./script/bootstrap: ruby: not found
Makefile:5: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 127

**Comment by moryzaky** [comment]
I have the same problem. Any update?

**Comment by NurseyitTursunkulov** [comment]
> I have the same problem. Any update?

no

**Comment by Arkariang** [comment]
You need to create your own Firebase account and download from there your `google-services.json`. We cannot share that information in a public repository as you can imagine.
Cheer folks and thanks for the interest in our source code
