### ISSUE TITLE
Error:(356, 28) No resource found that matches the given name (at 'value' with value '@string/koala_endpoint').

### ISSUE THREAD

**Issue by xiechuanyu** [kickstarter/android-oss#9]
Error:(356, 28) No resource found that matches the given name (at 'value' with value '@string/koala_endpoint').

**Comment by hotchemi** [comment]
You should try `make bootstrap` as described https://github.com/kickstarter/android-oss#getting-started.

**Comment by xiechuanyu** [comment]
Thanks, but how can i run '_make bootstrap_' on Windows ...

**Comment by MinaSamy** [comment]
You can download GNU Make for windows from here:
http://gnuwin32.sourceforge.net/packages/make.htm
